export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const DISABLED_PRODUCT_FROM_PRODUCTS = "DISABLED_PRODUCT_FROM_PRODUCTS";
export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";
export const SUBTRACT_PRODUCT_IN_CART = "SUBTRACT_PRODUCT_IN_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";